/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedFuelRouteImport } from './routes/_authenticated/fuel'
import { Route as AuthenticatedLabRouteImport } from './routes/_authenticated/lab'
import { Route as AuthenticatedPoseRouteImport } from './routes/_authenticated/pose'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedLabIndexRouteImport } from './routes/_authenticated/lab.index'
import { Route as AuthenticatedLabCaseIdRouteImport } from './routes/_authenticated/lab.$caseId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuelRoute = AuthenticatedFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabRoute = AuthenticatedLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoseRoute = AuthenticatedPoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabIndexRoute = AuthenticatedLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLabRoute,
} as any)
const AuthenticatedLabCaseIdRoute = AuthenticatedLabCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AuthenticatedLabRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/lab': typeof AuthenticatedLabRouteWithChildren
  '/pose': typeof AuthenticatedPoseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/lab/$caseId': typeof AuthenticatedLabCaseIdRoute
  '/lab/': typeof AuthenticatedLabIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/pose': typeof AuthenticatedPoseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/': typeof AuthenticatedIndexRoute
  '/lab/$caseId': typeof AuthenticatedLabCaseIdRoute
  '/lab': typeof AuthenticatedLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/fuel': typeof AuthenticatedFuelRoute
  '/_authenticated/lab': typeof AuthenticatedLabRouteWithChildren
  '/_authenticated/pose': typeof AuthenticatedPoseRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lab/$caseId': typeof AuthenticatedLabCaseIdRoute
  '/_authenticated/lab/': typeof AuthenticatedLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/coach'
    | '/fuel'
    | '/lab'
    | '/pose'
    | '/profile'
    | '/progress'
    | '/lab/$caseId'
    | '/lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/demo'
    | '/coach'
    | '/fuel'
    | '/pose'
    | '/profile'
    | '/progress'
    | '/'
    | '/lab/$caseId'
    | '/lab'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/_authenticated/coach'
    | '/_authenticated/fuel'
    | '/_authenticated/lab'
    | '/_authenticated/pose'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/'
    | '/_authenticated/lab/$caseId'
    | '/_authenticated/lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fuel': {
      id: '/_authenticated/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof AuthenticatedFuelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab': {
      id: '/_authenticated/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AuthenticatedLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pose': {
      id: '/_authenticated/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof AuthenticatedPoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab/': {
      id: '/_authenticated/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof AuthenticatedLabIndexRouteImport
      parentRoute: typeof AuthenticatedLabRoute
    }
    '/_authenticated/lab/$caseId': {
      id: '/_authenticated/lab/$caseId'
      path: '/$caseId'
      fullPath: '/lab/$caseId'
      preLoaderRoute: typeof AuthenticatedLabCaseIdRouteImport
      parentRoute: typeof AuthenticatedLabRoute
    }
  }
}

interface AuthenticatedLabRouteChildren {
  AuthenticatedLabCaseIdRoute: typeof AuthenticatedLabCaseIdRoute
  AuthenticatedLabIndexRoute: typeof AuthenticatedLabIndexRoute
}

const AuthenticatedLabRouteChildren: AuthenticatedLabRouteChildren = {
  AuthenticatedLabCaseIdRoute: AuthenticatedLabCaseIdRoute,
  AuthenticatedLabIndexRoute: AuthenticatedLabIndexRoute,
}

const AuthenticatedLabRouteWithChildren =
  AuthenticatedLabRoute._addFileChildren(AuthenticatedLabRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedFuelRoute: typeof AuthenticatedFuelRoute
  AuthenticatedLabRoute: typeof AuthenticatedLabRouteWithChildren
  AuthenticatedPoseRoute: typeof AuthenticatedPoseRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedFuelRoute: AuthenticatedFuelRoute,
  AuthenticatedLabRoute: AuthenticatedLabRouteWithChildren,
  AuthenticatedPoseRoute: AuthenticatedPoseRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
